version: 2.1

# Define the jobs we want to run for this project
jobs:
  install:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install:all

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm test

# Orchestrate our job run sequence
workflows:
  install_and_test:
    jobs:
      - install
      - test
      